version: "3.8"

services:
  daphne:
    build: .
    image: evaluator
    container_name: 'evaluator-daphne'
    command: daphne base.asgi:application
    network_mode: 'host'
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock

  rqworker:
    build: .
    image: evaluator
    container_name: 'evaluator-worker'
    command: poetry run ./manage.py rqworker
    network_mode: 'host'
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock

  # frontend:
  #   build: .
  #   image: evaluator
  #   container_name: 'evaluator-frontend'
  #   command: yarn dev
  #   network_mode: 'host'
  #   volumes:
  #     - .:/app
