# Generated by Django 3.2.7 on 2021-10-04 04:06

from django.db import migrations, models
import evaluator.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('input_examples', models.TextField()),
                ('output_examples', models.TextField()),
            ],
        ),
    ]
