# Generated by Django 3.2.7 on 2021-10-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0003_auto_20211018_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='topics',
            field=models.ManyToManyField(to='evaluator.Topic'),
        ),
    ]
