# Generated by Django 3.2.7 on 2021-10-28 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0004_task_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluator.task'),
        ),
    ]
