# Generated by Django 3.2.7 on 2021-12-03 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluator', '0005_alter_exercise_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('source_code', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Failed'), (1, 'Queued'), (2, 'Review'), (3, 'Tle'), (4, 'Accepted'), (5, 'Wrong Answer')])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_at', models.DateTimeField(null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluator.exercise')),
            ],
        ),
    ]
