# Generated by Django 3.2.7 on 2021-12-06 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0006_submission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'permissions': [('submit_exercise', 'Can submit an exercise')]},
        ),
    ]
