# Generated by Django 3.2.7 on 2022-01-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0008_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='output',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
