# Generated by Django 3.2.7 on 2022-04-06 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0010_auto_20220329_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluator.task'),
        ),
    ]
