# Generated by Django 3.2.7 on 2022-05-25 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0015_auto_20220507_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_example', models.TextField()),
                ('output_example', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='input_examples',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='output_examples',
        ),
        migrations.AddField(
            model_name='exercise',
            name='testcases',
            field=models.ManyToManyField(to='evaluator.Testcase'),
        ),
    ]
