# Generated by Django 3.2.7 on 2022-06-21 04:28

from django.db import migrations
from django.contrib.auth.hashers import make_password


def add_initial_groups_and_users(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    User = apps.get_model("auth", "User")

    Group.objects.create(name="Alumnos")
    teachers_group = Group.objects.create(name="Docente")

    teacher = User.objects.create(
        username="docente", password=make_password("12345678")
    )
    teacher.groups.set([teachers_group])


class Migration(migrations.Migration):

    dependencies = [
        ("evaluator", "0017_auto_20220527_2312"),
    ]

    operations = [migrations.RunPython(add_initial_groups_and_users)]
